"use client";

import React, { useState, useEffect } from "react";
import { ChartResponse, CurrentTransitResponse, calculateCurrentTransits } from "@/lib/api";
import { TransitTimeline } from "./TransitTimeline";
import { NorthIndianChart } from "./charts/NorthIndianChart";
import { PremiumLock } from "./PremiumLock";

interface TransitData {
  start_date: string;
  end_date: string;
  timelines: Record<string, any[]>;
  major_transits: any[];
  summary: Record<string, string>;
}

interface TransitCalculatorProps {
  chart: ChartResponse;
}

const LIFE_AREAS = [
  { id: "love_life", label: "💕 Love Life", description: "Romance, partnerships, relationships" },
  { id: "health", label: "🏥 Health", description: "Physical health and vitality" },
  { id: "career", label: "💼 Career", description: "Work, recognition, advancement" },
  { id: "finances", label: "💰 Finances", description: "Money, wealth, prosperity" },
  { id: "family", label: "👨‍👩‍👧‍👦 Family", description: "Family relationships and harmony" },
  { id: "self_confidence", label: "🦁 Self / Confidence", description: "Self-esteem, courage, personal power" },
];

const AREA_LABELS: Record<string, string> = {
  love_life: "Love Life",
  health: "Health",
  career: "Career",
  finances: "Finances",
  family: "Family",
  self_confidence: "Self / Confidence",
};

const AREA_ICONS: Record<string, string> = {
  love_life: "Love Life",
  health: "Health",
  career: "Career",
  finances: "Finances",
  family: "Family",
  self_confidence: "Self / Confidence",
};

async function downloadPdf(transitData: TransitData, selectedAreas: string[]) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const colors = {
    gold: [212, 175, 55] as [number, number, number],
    dark: [15, 23, 42] as [number, number, number],
    text: [51, 51, 51] as [number, number, number],
    lightGray: [120, 120, 140] as [number, number, number],
    green: [22, 163, 74] as [number, number, number],
    red: [220, 38, 38] as [number, number, number],
    neutral: [100, 116, 139] as [number, number, number],
    bgLight: [248, 250, 252] as [number, number, number],
    greenBg: [240, 253, 244] as [number, number, number],
    redBg: [254, 242, 242] as [number, number, number],
    neutralBg: [241, 245, 249] as [number, number, number],
    line: [200, 200, 210] as [number, number, number],
  };

  function checkPage(needed: number) {
    if (y + needed > pageH - 20) {
      // Footer on current page
      doc.setFontSize(7);
      doc.setTextColor(...colors.lightGray);
      doc.text("Generated by Jyotish — Vedic Astrology", pageW / 2, pageH - 8, { align: "center" });
      doc.addPage();
      y = margin;
    }
  }

  function drawLine() {
    doc.setDrawColor(...colors.line);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW - margin, y);
    y += 3;
  }

  // === HEADER ===
  doc.setFillColor(...colors.dark);
  doc.rect(0, 0, pageW, 38, "F");

  doc.setFontSize(22);
  doc.setTextColor(...colors.gold);
  doc.setFont("helvetica", "bold");
  doc.text("Vedic Transit Report", pageW / 2, 16, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(180, 180, 200);
  doc.setFont("helvetica", "normal");
  const startFmt = new Date(transitData.start_date).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const endFmt = new Date(transitData.end_date).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  doc.text(`${startFmt}  to  ${endFmt}`, pageW / 2, 25, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(140, 140, 160);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, pageW / 2, 33, { align: "center" });

  y = 48;

  // === SUMMARY TABLE ===
  doc.setFontSize(13);
  doc.setTextColor(...colors.text);
  doc.setFont("helvetica", "bold");
  doc.text("Overview", margin, y);
  y += 8;

  for (const areaId of selectedAreas) {
    const periods = transitData.timelines[areaId] || [];
    const favDays = periods.filter((p: { type: string }) => p.type === "favorable").reduce((s: number, p: { duration_days: number }) => s + p.duration_days, 0);
    const unfDays = periods.filter((p: { type: string }) => p.type === "unfavorable").reduce((s: number, p: { duration_days: number }) => s + p.duration_days, 0);
    const neuDays = periods.filter((p: { type: string }) => p.type === "neutral").reduce((s: number, p: { duration_days: number }) => s + p.duration_days, 0);
    const total = favDays + unfDays + neuDays;
    const pct = total > 0 ? Math.round((favDays / total) * 100) : 0;

    checkPage(10);

    // Background bar
    doc.setFillColor(...colors.bgLight);
    doc.roundedRect(margin, y - 4, contentW, 9, 2, 2, "F");

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(AREA_LABELS[areaId] || areaId, margin + 3, y + 1.5);

    // Favorable bar
    if (total > 0) {
      const barX = margin + 55;
      const barW = contentW - 85;
      const favW = (favDays / total) * barW;
      const unfW = (unfDays / total) * barW;

      doc.setFillColor(220, 220, 230);
      doc.roundedRect(barX, y - 2.5, barW, 5, 1.5, 1.5, "F");
      if (favW > 0) {
        doc.setFillColor(...colors.green);
        doc.roundedRect(barX, y - 2.5, Math.max(favW, 2), 5, 1.5, 1.5, "F");
      }
      if (unfW > 0) {
        doc.setFillColor(...colors.red);
        doc.roundedRect(barX + barW - unfW, y - 2.5, Math.max(unfW, 2), 5, 1.5, 1.5, "F");
      }

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.green);
      doc.text(`${pct}%`, pageW - margin - 3, y + 1.5, { align: "right" });
    }

    y += 12;
  }

  y += 5;
  drawLine();
  y += 3;

  // === DETAILED PERIODS PER LIFE AREA ===
  for (const areaId of selectedAreas) {
    const periods = transitData.timelines[areaId] || [];
    const summary = transitData.summary[areaId] || "";

    checkPage(25);

    // Section header
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.gold);
    doc.text(AREA_LABELS[areaId] || areaId, margin, y);
    y += 5;

    if (summary) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.lightGray);
      const summaryLines = doc.splitTextToSize(summary, contentW);
      doc.text(summaryLines, margin, y);
      y += summaryLines.length * 3.5 + 3;
    }

    if (periods.length === 0) {
      doc.setFontSize(9);
      doc.setTextColor(...colors.lightGray);
      doc.text("No significant transits detected.", margin + 3, y);
      y += 10;
      continue;
    }

    for (const p of periods) {
      checkPage(28);

      const isFav = p.type === "favorable";
      const isUnfav = p.type === "unfavorable";
      const bgColor = isFav ? colors.greenBg : isUnfav ? colors.redBg : colors.neutralBg;
      const accentColor = isFav ? colors.green : isUnfav ? colors.red : colors.neutral;
      const ratingLabel = p.rating_label || p.type;

      const dur = p.duration_days >= 30
        ? `~${Math.round(p.duration_days / 30)} month(s)`
        : `${p.duration_days} day(s)`;
      const dateFmt = (d: string) => new Date(d).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });

      // Card background
      doc.setFillColor(...bgColor);
      doc.roundedRect(margin, y - 2, contentW, 22, 2, 2, "F");

      // Left accent bar
      doc.setFillColor(...accentColor);
      doc.rect(margin, y - 2, 2, 22, "F");

      // Rating badge
      doc.setFillColor(...accentColor);
      doc.roundedRect(margin + 5, y, 30, 5, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(ratingLabel, margin + 20, y + 3.5, { align: "center" });

      // Duration
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.text);
      doc.text(dur, pageW - margin - 3, y + 3.5, { align: "right" });

      // Date range
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.text);
      doc.text(`${dateFmt(p.start_date)}  —  ${dateFmt(p.end_date)}`, margin + 5, y + 11);

      // Planets
      if (p.active_planets?.length) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...accentColor);
        doc.text(`Planets: ${p.active_planets.join(", ")}`, margin + 5, y + 16);
      }

      y += 26;

      // Guidance (wrapped text below card)
      if (p.guidance) {
        checkPage(12);
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(...colors.lightGray);
        const guidanceLines = doc.splitTextToSize(p.guidance, contentW - 10);
        doc.text(guidanceLines, margin + 5, y);
        y += guidanceLines.length * 3.2 + 4;
      }
    }

    y += 5;
    drawLine();
    y += 3;
  }

  // === MAJOR TRANSIT EVENTS ===
  if (transitData.major_transits?.length) {
    checkPage(20);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.gold);
    doc.text("Major Transit Events", margin, y);
    y += 8;

    for (const t of transitData.major_transits.slice(0, 15)) {
      checkPage(7);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.text);
      doc.text(t.date, margin + 3, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.lightGray);
      doc.text(`${t.planet} conjunction  (transit ${t.transit_position.toFixed(1)} > natal ${t.natal_position.toFixed(1)})`, margin + 28, y);
      y += 5;
    }
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(...colors.lightGray);
  doc.text("Generated by Jyotish — Vedic Astrology", pageW / 2, pageH - 8, { align: "center" });

  doc.save(`transit-report-${transitData.start_date}.pdf`);
}

export function TransitCalculator({ chart }: TransitCalculatorProps) {
  const [startDate, setStartDate] = useState(
    new Date().toISOString().split("T")[0]
  );
  const [endDate, setEndDate] = useState(
    new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split("T")[0]
  );
  const [selectedAreas, setSelectedAreas] = useState<string[]>(
    LIFE_AREAS.map(a => a.id)
  );
  const [transitData, setTransitData] = useState<TransitData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Current transit chart state
  const [currentTransit, setCurrentTransit] = useState<CurrentTransitResponse | null>(null);
  const [transitChartLoading, setTransitChartLoading] = useState(true);

  useEffect(() => {
    calculateCurrentTransits(chart.ayanamsha_value, chart.lagna_degree)
      .then(setCurrentTransit)
      .catch(() => {})
      .finally(() => setTransitChartLoading(false));
  }, [chart.ayanamsha_value, chart.lagna_degree]);

  const handleAreaToggle = (areaId: string) => {
    setSelectedAreas(prev =>
      prev.includes(areaId)
        ? prev.filter(a => a !== areaId)
        : [...prev, areaId]
    );
  };

  const handleCalculate = async () => {
    if (!startDate || !endDate) {
      setError("Please select both start and end dates");
      return;
    }

    if (new Date(startDate) >= new Date(endDate)) {
      setError("Start date must be before end date");
      return;
    }

    if (selectedAreas.length === 0) {
      setError("Please select at least one life area");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const response = await fetch("/api/chart/transits", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chart_data: chart,
          start_date: startDate,
          end_date: endDate,
          life_areas: selectedAreas,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || "Failed to calculate transits");
      }

      const data = await response.json();
      setTransitData(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const PLANET_ABBR: Record<string, string> = {
    Sun: "Su", Moon: "Mo", Mars: "Ma", Mercury: "Me",
    Jupiter: "Ju", Venus: "Ve", Saturn: "Sa", Rahu: "Ra", Ketu: "Ke",
  };

  return (
    <div className="space-y-6">
      {/* Current Transit Chart */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
        <h3 className="text-lg font-semibold text-amber-400 mb-1">🌍 Current Transit Chart</h3>
        <p className="text-xs text-slate-500 mb-4">
          Planet positions for today ({currentTransit?.transit_date ?? "loading..."}) in your natal house framework
        </p>

        {transitChartLoading && (
          <div className="flex items-center justify-center h-40 text-slate-500">
            <div className="text-center space-y-3">
              <div className="w-6 h-6 border-2 border-amber-500 border-t-transparent rounded-full animate-spin mx-auto" />
              <p className="text-sm">Calculating current transits…</p>
            </div>
          </div>
        )}

        {currentTransit && !transitChartLoading && (
          <div className="space-y-4">
            <NorthIndianChart
              lagna={currentTransit.lagna}
              lagna_degree={currentTransit.lagna_degree}
              planets={currentTransit.planets}
              houses={currentTransit.houses}
            />

            {/* Planet position summary grid */}
            <div className="grid grid-cols-3 sm:grid-cols-5 gap-2">
              {currentTransit.planets.map(p => (
                <div
                  key={p.name}
                  className="bg-slate-800/60 border border-slate-700 rounded-lg px-2 py-1.5 text-center"
                >
                  <p className="text-xs font-bold text-slate-300">
                    {PLANET_ABBR[p.name] ?? p.name}{p.is_retrograde ? " ᴿ" : ""}
                  </p>
                  <p className="text-xs text-slate-500">
                    {p.rashi.slice(0, 3)} {p.degree_in_rashi.toFixed(1)}°
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Configuration Panel — Premium */}
      <PremiumLock>
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-6">
        {/* Date Range */}
        <div>
          <h3 className="text-sm font-semibold text-amber-400 mb-3">📅 Select Date Range</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-medium text-slate-400 block mb-2">
                Start Date
              </label>
              <input
                type="date"
                value={startDate}
                onChange={e => setStartDate(e.target.value)}
                className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 text-sm focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/50"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-slate-400 block mb-2">
                End Date
              </label>
              <input
                type="date"
                value={endDate}
                onChange={e => setEndDate(e.target.value)}
                className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 text-sm focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/50"
              />
            </div>
          </div>
        </div>

        {/* Life Areas Selection */}
        <div>
          <h3 className="text-sm font-semibold text-amber-400 mb-3">🎯 Select Life Areas</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {LIFE_AREAS.map(area => (
              <button
                key={area.id}
                onClick={() => handleAreaToggle(area.id)}
                className={`text-left p-3 rounded-lg border transition-all ${
                  selectedAreas.includes(area.id)
                    ? "bg-amber-900/30 border-amber-600 ring-1 ring-amber-500/50"
                    : "bg-slate-800/50 border-slate-700 hover:border-slate-600"
                }`}
              >
                <div className="font-medium text-slate-200">{area.label}</div>
                <div className="text-xs text-slate-400 mt-1">{area.description}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-900/30 border border-red-700 rounded-lg p-3">
            <p className="text-sm text-red-300">⚠️ {error}</p>
          </div>
        )}

        {/* Calculate Button */}
        <button
          onClick={handleCalculate}
          disabled={loading}
          className="w-full bg-amber-600 hover:bg-amber-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white font-semibold py-3 rounded-lg transition-colors"
        >
          {loading ? (
            <span className="flex items-center justify-center gap-2">
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Calculating Transits...
            </span>
          ) : (
            "Calculate Transit Periods ✨"
          )}
        </button>
      </div>

      {/* Results */}
      {transitData && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div>
              <h2 className="text-xl font-bold text-amber-400 mb-1">Transit Analysis Results</h2>
              <p className="text-sm text-slate-400">
                Analysis period: {new Date(transitData.start_date).toLocaleDateString("en-IN")} to{" "}
                {new Date(transitData.end_date).toLocaleDateString("en-IN")}
              </p>
            </div>
            {/* Download PDF */}
            <button
              onClick={() => downloadPdf(transitData, selectedAreas)}
              className="flex items-center gap-1.5 bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-colors flex-shrink-0"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download PDF
            </button>
          </div>

          {/* Timeline for each life area */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {selectedAreas.map(areaId => (
              <div
                key={areaId}
                className="bg-slate-900 border border-slate-800 rounded-xl p-6"
              >
                <TransitTimeline
                  lifeArea={areaId}
                  periods={transitData.timelines[areaId] || []}
                  summary={transitData.summary[areaId] || ""}
                />
              </div>
            ))}
          </div>

          {/* Major Transit Events */}
          {transitData.major_transits.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-amber-400 mb-4">
                🌙 Major Transit Events
              </h3>
              <div className="space-y-3">
                {transitData.major_transits.slice(0, 10).map((transit, idx) => (
                  <div key={idx} className="border border-slate-700 rounded-lg p-3 flex items-center justify-between">
                    <div>
                      <p className="font-medium text-slate-200">{transit.planet} Conjunction</p>
                      <p className="text-xs text-slate-400">
                        Transiting {transit.transit_position.toFixed(1)}° meets natal {transit.natal_position.toFixed(1)}°
                      </p>
                    </div>
                    <p className="text-sm font-semibold text-amber-400">
                      {new Date(transit.date).toLocaleDateString("en-IN")}
                    </p>
                  </div>
                ))}
                {transitData.major_transits.length > 10 && (
                  <p className="text-xs text-slate-500 text-center pt-2">
                    +{transitData.major_transits.length - 10} more events
                  </p>
                )}
              </div>
            </div>
          )}
        </div>
      )}
      </PremiumLock>
    </div>
  );
}
