"use client";

import React, { useState } from "react";
import { ChartResponse } from "@/lib/api";
import { AyurvedicReport } from "@/lib/ayurvedicReport";

interface Props {
  report: AyurvedicReport;
  chart: ChartResponse;
  name?: string;
}

// ─── PDF Generation ─────────────────────────────────────────────────────────
async function downloadReportPdf(report: AyurvedicReport, chart: ChartResponse, name?: string) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const colors = {
    gold: [212, 175, 55] as [number, number, number],
    dark: [15, 23, 42] as [number, number, number],
    text: [40, 40, 50] as [number, number, number],
    gray: [120, 120, 140] as [number, number, number],
    green: [22, 163, 74] as [number, number, number],
    red: [220, 38, 38] as [number, number, number],
    amber: [217, 119, 6] as [number, number, number],
    blue: [59, 130, 246] as [number, number, number],
    bgLight: [248, 250, 252] as [number, number, number],
    line: [200, 200, 210] as [number, number, number],
  };

  function footer() {
    doc.setFontSize(7);
    doc.setTextColor(...colors.gray);
    doc.text("Generated by Jyotish — Vedic Astrology & Ayurveda", pageW / 2, pageH - 8, { align: "center" });
  }

  function checkPage(needed: number) {
    if (y + needed > pageH - 18) {
      footer();
      doc.addPage();
      y = margin;
    }
  }

  function drawLine() {
    doc.setDrawColor(...colors.line);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  }

  function sectionTitle(icon: string, title: string) {
    checkPage(16);
    y += 4;
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(margin, y - 5, contentW, 10, 2, 2, "F");
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`${icon}  ${title}`, margin + 4, y + 1.5);
    y += 10;
  }

  function bodyText(text: string, maxWidth?: number) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.text);
    const lines = doc.splitTextToSize(text, maxWidth || contentW);
    for (const line of lines) {
      checkPage(5);
      doc.text(line, margin, y);
      y += 4;
    }
  }

  function labelValue(label: string, value: string, indent = 0) {
    checkPage(6);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.gray);
    doc.text(label + ":", margin + indent, y);
    const labelW = doc.getTextWidth(label + ": ");
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.text);
    doc.text(value, margin + indent + labelW, y);
    y += 5;
  }

  // ═══ HEADER ═══
  doc.setFillColor(...colors.dark);
  doc.rect(0, 0, pageW, 42, "F");

  doc.setFontSize(22);
  doc.setTextColor(...colors.gold);
  doc.setFont("helvetica", "bold");
  doc.text("Ayurvedic Wellness Report", pageW / 2, 16, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(200, 200, 220);
  doc.setFont("helvetica", "normal");
  const subtitle = `${name ? name + " | " : ""}${chart.lagna} Lagna | ${chart.place.split(",")[0]} | ${chart.date} ${chart.time}`;
  doc.text(subtitle, pageW / 2, 26, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(140, 140, 160);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, pageW / 2, 35, { align: "center" });

  y = 50;

  // ═══ 1. DOSHA CONSTITUTION ═══
  sectionTitle("*", "Dosha Constitution (Prakriti)");

  const doshas = [
    { name: "Vata", pct: report.doshaConstitution.vata, color: colors.blue },
    { name: "Pitta", pct: report.doshaConstitution.pitta, color: colors.red },
    { name: "Kapha", pct: report.doshaConstitution.kapha, color: colors.green },
  ];

  for (const d of doshas) {
    checkPage(8);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(`${d.name}: ${d.pct}%`, margin, y);

    const barX = margin + 30;
    const barW = contentW - 30;
    doc.setFillColor(230, 230, 240);
    doc.roundedRect(barX, y - 3, barW, 4, 1, 1, "F");
    doc.setFillColor(...d.color);
    doc.roundedRect(barX, y - 3, Math.max((d.pct / 100) * barW, 2), 4, 1, 1, "F");
    y += 7;
  }

  checkPage(6);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.amber);
  doc.text(`Primary: ${report.doshaConstitution.primaryDosha}${report.doshaConstitution.secondaryDosha ? ` | Secondary: ${report.doshaConstitution.secondaryDosha}` : ""}`, margin, y);
  y += 5;

  bodyText(report.doshaConstitution.description);
  y += 2;

  // ═══ 2. BODY TYPE PROFILE ═══
  sectionTitle("@", "Body Type Profile");

  const bodyAttrs = [
    ["Primary Dosha", report.bodyTypeProfile.primaryDosha],
    ["Secondary Dosha", report.bodyTypeProfile.secondaryDosha],
    ["Frame", report.bodyTypeProfile.frame],
    ["Metabolism", report.bodyTypeProfile.metabolism],
    ["Skin Type", report.bodyTypeProfile.skinType],
    ["Hair", report.bodyTypeProfile.hair],
    ["Digestion Pattern", report.bodyTypeProfile.digestionPattern],
    ["Sleep Pattern", report.bodyTypeProfile.sleepPattern],
    ["Energy Pattern", report.bodyTypeProfile.energyPattern],
  ];

  for (const [label, value] of bodyAttrs) {
    if (value) labelValue(label, value);
  }

  if (report.bodyTypeProfile.summary) {
    y += 2;
    bodyText(report.bodyTypeProfile.summary);
  }
  y += 2;

  // ═══ 3. HEALTH PLANET ANALYSIS ═══
  sectionTitle("*", "Health Planet Analysis");

  for (const hp of report.healthPlanetAnalysis) {
    checkPage(20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(hp.planet, margin, y);

    const strengthColor = hp.strength === "strong" ? colors.green : hp.strength === "moderate" ? colors.amber : colors.red;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...strengthColor);
    doc.text(`[${hp.strength.toUpperCase()}]`, margin + doc.getTextWidth(hp.planet + "  ") + 2, y);

    y += 4.5;
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text(`${hp.rashi} | House ${hp.house}${hp.dignity ? ` | ${hp.dignity}` : ""}${hp.isRetrograde ? " | Retrograde" : ""} | Areas: ${hp.bodyAreas}`, margin, y);
    y += 4.5;

    bodyText(hp.interpretation);
    y += 2;
  }

  // ═══ 4. HOUSE HEALTH ANALYSIS ═══
  sectionTitle("#", "Health House Analysis");

  for (const ha of report.houseHealthAnalysis) {
    checkPage(18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(`House ${ha.house} - ${ha.title}`, margin, y);

    const strengthColor = ha.lordStrength === "strong" ? colors.green : ha.lordStrength === "moderate" ? colors.amber : colors.red;
    doc.setFontSize(8);
    doc.setTextColor(...strengthColor);
    doc.text(`[${ha.lordStrength.toUpperCase()}]`, margin + doc.getTextWidth(`House ${ha.house} - ${ha.title}  `) + 2, y);

    y += 4.5;
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text(`${ha.rashi} | Lord: ${ha.lord} in ${ha.lordPlacement}${ha.occupants.length > 0 ? ` | Occupants: ${ha.occupants.join(", ")}` : ""}`, margin, y);
    y += 4.5;

    bodyText(ha.interpretation);
    y += 2;
  }

  // ═══ 5. VULNERABLE BODY AREAS ═══
  sectionTitle("!", "Vulnerable Body Areas");

  for (const va of report.vulnerableAreas) {
    checkPage(12);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.red);
    doc.text(va.bodyPart, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.gray);
    doc.text(` (${va.rashi})`, margin + doc.getTextWidth(va.bodyPart), y);
    y += 4.5;
    bodyText(va.reason);
    y += 2;
  }

  // ═══ 6. DIETARY RECOMMENDATIONS ═══
  sectionTitle("+", "Dietary Recommendations");

  if (report.dietaryRecommendations.generalGuidance) {
    bodyText(report.dietaryRecommendations.generalGuidance);
    y += 2;
  }

  const favorFoods = report.dietaryRecommendations.foods.filter(f => f.action === "favor");
  const avoidFoods = report.dietaryRecommendations.foods.filter(f => f.action === "avoid");

  if (favorFoods.length > 0) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.green);
    doc.text("Foods to Favor:", margin, y);
    y += 5;
    for (const f of favorFoods) {
      checkPage(5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.text);
      doc.text(`+ ${f.food}${f.reasoning ? ` - ${f.reasoning}` : ""}`, margin + 3, y);
      y += 4;
    }
    y += 2;
  }

  if (avoidFoods.length > 0) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.red);
    doc.text("Foods to Reduce:", margin, y);
    y += 5;
    for (const f of avoidFoods) {
      checkPage(5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.text);
      doc.text(`- ${f.food}${f.reasoning ? ` - ${f.reasoning}` : ""}`, margin + 3, y);
      y += 4;
    }
    y += 2;
  }

  if (report.dietaryRecommendations.mealTiming) {
    labelValue("Meal Timing", report.dietaryRecommendations.mealTiming);
    y += 1;
  }

  if (report.dietaryRecommendations.spices.length > 0) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.amber);
    doc.text("Recommended Spices:", margin, y);
    y += 5;
    for (const s of report.dietaryRecommendations.spices) {
      checkPage(5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.text);
      doc.text(`${s.name} - ${s.benefit}`, margin + 3, y);
      y += 4;
    }
    y += 2;
  }

  // ═══ 7. YOGA & EXERCISE ═══
  sectionTitle("~", "Yoga & Exercise Recommendations");

  for (const a of report.yogaExerciseRecommendations.asanas) {
    checkPage(14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(a.name, margin, y);
    y += 4.5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...colors.gray);
    const descLines = doc.splitTextToSize(a.description, contentW);
    for (const line of descLines) {
      checkPage(4);
      doc.text(line, margin, y);
      y += 3.5;
    }
    doc.setFont("helvetica", "normal");
    bodyText(a.reasoning);
    y += 2;
  }

  if (report.yogaExerciseRecommendations.pranayama.length > 0) {
    checkPage(8);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.blue);
    doc.text("Pranayama:", margin, y);
    y += 5;
    for (const p of report.yogaExerciseRecommendations.pranayama) {
      checkPage(8);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.text);
      doc.text(p.name, margin + 3, y);
      y += 4;
      bodyText(p.description);
      y += 1;
    }
  }

  if (report.yogaExerciseRecommendations.exerciseType) {
    labelValue("Exercise Type", `${report.yogaExerciseRecommendations.exerciseType} (${report.yogaExerciseRecommendations.intensity})`);
  }
  if (report.yogaExerciseRecommendations.bestTimeOfDay) {
    labelValue("Best Time", report.yogaExerciseRecommendations.bestTimeOfDay);
  }
  y += 2;

  // ═══ 8. LIFESTYLE RECOMMENDATIONS ═══
  sectionTitle(">", "Lifestyle Recommendations");

  if (report.lifestyleRecommendations.sleepSchedule) {
    labelValue("Sleep Schedule", report.lifestyleRecommendations.sleepSchedule);
    y += 1;
  }
  if (report.lifestyleRecommendations.stressManagement) {
    checkPage(6);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.gray);
    doc.text("Stress Management:", margin, y);
    y += 4;
    bodyText(report.lifestyleRecommendations.stressManagement);
    y += 1;
  }

  if (report.lifestyleRecommendations.seasonalAdvice.length > 0) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.amber);
    doc.text("Seasonal Advice:", margin, y);
    y += 5;
    for (const sa of report.lifestyleRecommendations.seasonalAdvice) {
      checkPage(5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.text);
      doc.text(`${sa.season}: `, margin + 3, y);
      doc.setFont("helvetica", "normal");
      const advLines = doc.splitTextToSize(sa.advice, contentW - 5);
      for (let li = 0; li < advLines.length; li++) {
        if (li === 0) {
          doc.text(advLines[li], margin + 3 + doc.getTextWidth(`${sa.season}: `), y);
        } else {
          y += 4;
          checkPage(4);
          doc.text(advLines[li], margin + 3, y);
        }
      }
      y += 5;
    }
  }

  if (report.lifestyleRecommendations.dailyRoutine.length > 0) {
    checkPage(8);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.amber);
    doc.text("Daily Routine (Dinacharya):", margin, y);
    y += 5;
    for (const dr of report.lifestyleRecommendations.dailyRoutine) {
      checkPage(5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.amber);
      doc.text(dr.time, margin + 3, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.text);
      doc.text(dr.activity, margin + 25, y);
      y += 4.5;
    }
    y += 2;
  }

  // ═══ 9. HEALTH PERIOD TIMELINE ═══
  sectionTitle("=", "Health Period Timeline");

  for (const hp of report.healthPeriodTimeline) {
    checkPage(16);
    const typeColor = hp.type === "favorable" ? colors.green : hp.type === "cautious" ? colors.amber : colors.red;
    const typeLabel = hp.type === "favorable" ? "FAVORABLE" : hp.type === "cautious" ? "CAUTION" : "NEUTRAL";

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.text);
    doc.text(`${hp.dashaLord}${hp.isCurrent ? " (Current)" : ""}`, margin, y);
    doc.setFontSize(8);
    doc.setTextColor(...typeColor);
    doc.text(`[${typeLabel}]`, margin + doc.getTextWidth(`${hp.dashaLord}${hp.isCurrent ? " (Current)" : ""}  `) + 2, y);

    y += 4.5;
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text(`${hp.startDate} - ${hp.endDate}`, margin, y);
    y += 4.5;

    bodyText(hp.interpretation);
    y += 2;
  }

  // ═══ 10. REMEDIES ═══
  sectionTitle("*", "Remedies & Recommendations");

  for (const r of report.remedies) {
    checkPage(14);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.amber);
    doc.text(`[${r.category}]`, margin, y);
    doc.setFontSize(9);
    doc.setTextColor(...colors.text);
    doc.text(r.title, margin + doc.getTextWidth(`[${r.category}]  `) + 1, y);
    y += 4.5;
    bodyText(r.description);
    y += 2;
  }

  // ═══ DISCLAIMER ═══
  checkPage(20);
  y += 4;
  drawLine();
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...colors.gray);
  const disclaimer = "Disclaimer: This report is based on traditional Vedic astrology and Ayurvedic principles. It is for informational and wellness purposes only and does not constitute medical advice. Always consult qualified healthcare professionals for medical decisions.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentW);
  for (const line of disclaimerLines) {
    checkPage(4);
    doc.text(line, margin, y);
    y += 3.5;
  }

  footer();

  // Save
  const fileName = `Ayurvedic-Report${name ? `-${name.replace(/\s+/g, "-")}` : ""}-${chart.date}.pdf`;
  doc.save(fileName);
}

function Section({ title, icon, children }: { title: string; icon: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="border border-slate-800 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full px-5 py-3.5 flex items-center justify-between bg-slate-800/30 hover:bg-slate-800/50 transition-colors"
      >
        <span className="text-sm font-semibold text-slate-200 flex items-center gap-2">
          <span className="text-lg">{icon}</span>
          {title}
        </span>
        <span className={`text-slate-500 transition-transform ${open ? "rotate-180" : ""}`}>
          {"\u25B4"}
        </span>
      </button>
      {open && <div className="p-5 space-y-4">{children}</div>}
    </div>
  );
}

function DoshaBar({ dosha, pct, color }: { dosha: string; pct: number; color: string }) {
  return (
    <div className="space-y-1">
      <div className="flex items-center justify-between text-xs">
        <span className="text-slate-300 font-medium">{dosha}</span>
        <span className="text-slate-400">{pct}%</span>
      </div>
      <div className="h-2.5 bg-slate-800 rounded-full overflow-hidden">
        <div className={`h-full rounded-full ${color}`} style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}

function StrengthBadge({ strength }: { strength: string }) {
  const cls =
    strength === "strong"
      ? "bg-green-500/10 text-green-400 border-green-500/20"
      : strength === "moderate"
      ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
      : "bg-red-500/10 text-red-400 border-red-500/20";
  return (
    <span className={`text-xs px-2 py-0.5 rounded-full border ${cls}`}>
      {strength.charAt(0).toUpperCase() + strength.slice(1)}
    </span>
  );
}

export function AyurvedicReportView({ report, chart, name }: Props) {
  const doshaColors: Record<string, string> = {
    Vata: "bg-blue-500",
    Pitta: "bg-red-500",
    Kapha: "bg-green-500",
  };

  return (
    <div className="space-y-5">
      {/* Report header */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 text-center space-y-2">
        <p className="text-2xl">{"\u{1F33F}"}</p>
        <h2 className="text-xl font-bold text-amber-400">Ayurvedic Wellness Report</h2>
        <p className="text-sm text-slate-400">
          {name ? `${name} \u00b7 ` : ""}
          {chart.lagna} Lagna \u00b7 {chart.place.split(",")[0]} \u00b7 {chart.date} {chart.time}
        </p>
        <p className="text-xs text-slate-600">
          Generated on {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
        </p>
      </div>

      {/* 1. Dosha Constitution */}
      <Section title="Dosha Constitution (Prakriti)" icon={"\u{2697}\uFE0F"}>
        <div className="space-y-3">
          {[
            { dosha: "Vata", pct: report.doshaConstitution.vata },
            { dosha: "Pitta", pct: report.doshaConstitution.pitta },
            { dosha: "Kapha", pct: report.doshaConstitution.kapha },
          ].map((d) => (
            <DoshaBar
              key={d.dosha}
              dosha={d.dosha}
              pct={d.pct}
              color={doshaColors[d.dosha] || "bg-slate-500"}
            />
          ))}
        </div>
        <div className="bg-slate-800/40 rounded-lg p-4 mt-3">
          <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Your Constitution</p>
          <p className="text-sm text-slate-200 font-medium">
            {report.doshaConstitution.primaryDosha}
            {report.doshaConstitution.secondaryDosha ? `–${report.doshaConstitution.secondaryDosha}` : ""} Prakriti
          </p>
          <p className="text-xs text-slate-400 mt-2 leading-relaxed">
            {report.doshaConstitution.description}
          </p>
        </div>
      </Section>

      {/* 2. Body Type */}
      <Section title="Body Type Profile" icon={"\u{1F9D8}"}>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {[
            { label: "Primary Dosha", value: report.bodyTypeProfile.primaryDosha },
            { label: "Secondary Dosha", value: report.bodyTypeProfile.secondaryDosha },
            { label: "Frame", value: report.bodyTypeProfile.frame },
            { label: "Metabolism", value: report.bodyTypeProfile.metabolism },
            { label: "Skin Type", value: report.bodyTypeProfile.skinType },
            { label: "Hair", value: report.bodyTypeProfile.hair },
            { label: "Digestion Pattern", value: report.bodyTypeProfile.digestionPattern },
            { label: "Sleep Pattern", value: report.bodyTypeProfile.sleepPattern },
            { label: "Energy Pattern", value: report.bodyTypeProfile.energyPattern },
          ].map((attr) => (
            <div key={attr.label} className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs text-slate-500 uppercase tracking-wide">{attr.label}</p>
              <p className="text-sm text-slate-200 mt-0.5">{attr.value}</p>
            </div>
          ))}
        </div>
        <p className="text-xs text-slate-400 leading-relaxed mt-2">{report.bodyTypeProfile.summary}</p>
      </Section>

      {/* 3. Health Planet Analysis */}
      <Section title="Health Planet Analysis" icon={"\u{2B50}"}>
        <div className="space-y-3">
          {report.healthPlanetAnalysis.map((hp) => (
            <div
              key={hp.planet}
              className="bg-slate-800/30 rounded-lg p-4 space-y-2"
            >
              <div className="flex items-center justify-between">
                <div>
                  <span className="text-sm font-semibold text-slate-200">{hp.planet}</span>
                  <span className="text-xs text-slate-500 ml-2">
                    {hp.rashi} \u00b7 House {hp.house}
                    {hp.dignity ? ` \u00b7 ${hp.dignity}` : ""}
                    {hp.isRetrograde ? " \u00b7 R" : ""}
                  </span>
                </div>
                <StrengthBadge strength={hp.strength} />
              </div>
              <p className="text-xs text-slate-500 uppercase tracking-wide">{hp.bodyAreas}</p>
              <p className="text-xs text-slate-400 leading-relaxed">{hp.interpretation}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 4. House Health Analysis */}
      <Section title="Health House Analysis" icon={"\u{1F3E0}"}>
        <div className="space-y-3">
          {report.houseHealthAnalysis.map((ha) => (
            <div key={ha.house} className="bg-slate-800/30 rounded-lg p-4 space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-sm font-semibold text-slate-200">
                  House {ha.house} {"\u2014"} {ha.title}
                </span>
                <StrengthBadge strength={ha.lordStrength} />
              </div>
              <p className="text-xs text-slate-500">
                {ha.rashi} \u00b7 Lord: {ha.lord} in {ha.lordPlacement}
                {ha.occupants.length > 0 ? ` \u00b7 Occupied by: ${ha.occupants.join(", ")}` : ""}
              </p>
              <p className="text-xs text-slate-400 leading-relaxed mt-1">{ha.interpretation}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 5. Vulnerable Body Areas */}
      <Section title="Vulnerable Body Areas" icon={"\u{26A0}\uFE0F"}>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {report.vulnerableAreas.map((va, i) => (
            <div key={i} className="bg-red-500/5 border border-red-500/10 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200">{va.bodyPart}</p>
              <p className="text-xs text-slate-500">{va.rashi}</p>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">{va.reason}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 6. Dietary Recommendations */}
      <Section title="Dietary Recommendations" icon={"\u{1F957}"}>
        <div className="space-y-4">
          {report.dietaryRecommendations.generalGuidance && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs font-semibold text-slate-300 mb-1">General Guidance</p>
              <p className="text-xs text-slate-400 leading-relaxed">{report.dietaryRecommendations.generalGuidance}</p>
            </div>
          )}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="bg-green-500/5 border border-green-500/10 rounded-lg p-3">
              <p className="text-xs font-semibold text-green-400 uppercase tracking-wide mb-2">
                Foods to Favor
              </p>
              <ul className="space-y-1">
                {report.dietaryRecommendations.foods.filter((f) => f.action === "favor").map((f, i) => (
                  <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5">
                    <span className="text-green-500 mt-0.5">{"\u2713"}</span>
                    <span>{f.food}{f.reasoning ? ` \u2014 ${f.reasoning}` : ""}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-red-500/5 border border-red-500/10 rounded-lg p-3">
              <p className="text-xs font-semibold text-red-400 uppercase tracking-wide mb-2">
                Foods to Reduce
              </p>
              <ul className="space-y-1">
                {report.dietaryRecommendations.foods.filter((f) => f.action === "avoid").map((f, i) => (
                  <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5">
                    <span className="text-red-500 mt-0.5">{"\u2717"}</span>
                    <span>{f.food}{f.reasoning ? ` \u2014 ${f.reasoning}` : ""}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          {report.dietaryRecommendations.mealTiming && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs font-semibold text-slate-300 mb-1">Meal Timing</p>
              <p className="text-xs text-slate-400 leading-relaxed">{report.dietaryRecommendations.mealTiming}</p>
            </div>
          )}
          {report.dietaryRecommendations.spices.length > 0 && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs font-semibold text-slate-300 mb-1">Recommended Spices</p>
              <div className="flex flex-wrap gap-1.5 mt-1">
                {report.dietaryRecommendations.spices.map((s) => (
                  <span
                    key={s.name}
                    className="text-xs bg-amber-500/10 text-amber-400 border border-amber-500/20 rounded-full px-2 py-0.5"
                    title={s.benefit}
                  >
                    {s.name}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </Section>

      {/* 7. Yoga & Exercise */}
      <Section title="Yoga & Exercise Recommendations" icon={"\u{1F9D8}\u200D\u2640\uFE0F"}>
        <div className="space-y-3">
          {report.yogaExerciseRecommendations.asanas.map((a, i) => (
            <div key={i} className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200">{a.name}</p>
              <p className="text-xs text-slate-500 mt-0.5">{a.description}</p>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">{a.reasoning}</p>
            </div>
          ))}
          {report.yogaExerciseRecommendations.pranayama.length > 0 && (
            <div className="bg-blue-500/5 border border-blue-500/10 rounded-lg p-3 space-y-2">
              <p className="text-xs font-semibold text-blue-400 uppercase tracking-wide mb-1">
                Pranayama
              </p>
              {report.yogaExerciseRecommendations.pranayama.map((p, i) => (
                <div key={i}>
                  <p className="text-xs text-slate-200 font-medium">{p.name}</p>
                  <p className="text-xs text-slate-400 leading-relaxed">{p.description}</p>
                </div>
              ))}
            </div>
          )}
          {report.yogaExerciseRecommendations.exerciseType && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs font-semibold text-slate-300 mb-1">Exercise Type ({report.yogaExerciseRecommendations.intensity})</p>
              <p className="text-xs text-slate-400 leading-relaxed">{report.yogaExerciseRecommendations.exerciseType}</p>
            </div>
          )}
          {report.yogaExerciseRecommendations.bestTimeOfDay && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-xs font-semibold text-slate-300 mb-1">Best Time for Exercise</p>
              <p className="text-xs text-slate-400">{report.yogaExerciseRecommendations.bestTimeOfDay}</p>
            </div>
          )}
        </div>
      </Section>

      {/* 8. Lifestyle Recommendations */}
      <Section title="Lifestyle Recommendations" icon={"\u{1F305}"}>
        <div className="space-y-3">
          {report.lifestyleRecommendations.sleepSchedule && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200">Sleep Schedule</p>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">{report.lifestyleRecommendations.sleepSchedule}</p>
            </div>
          )}
          {report.lifestyleRecommendations.stressManagement && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200">Stress Management</p>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">{report.lifestyleRecommendations.stressManagement}</p>
            </div>
          )}
          {report.lifestyleRecommendations.seasonalAdvice.length > 0 && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200 mb-2">Seasonal Advice</p>
              {report.lifestyleRecommendations.seasonalAdvice.map((sa, i) => (
                <div key={i} className="mb-1">
                  <span className="text-xs text-amber-400 font-medium">{sa.season}:</span>
                  <span className="text-xs text-slate-400 ml-1">{sa.advice}</span>
                </div>
              ))}
            </div>
          )}
          {report.lifestyleRecommendations.dailyRoutine.length > 0 && (
            <div className="bg-slate-800/30 rounded-lg p-3">
              <p className="text-sm font-semibold text-slate-200 mb-2">Daily Routine</p>
              {report.lifestyleRecommendations.dailyRoutine.map((dr, i) => (
                <div key={i} className="flex gap-2 mb-1">
                  <span className="text-xs text-amber-400 font-medium whitespace-nowrap">{dr.time}</span>
                  <span className="text-xs text-slate-400">{dr.activity}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </Section>

      {/* 9. Health Period Timeline */}
      <Section title="Health Period Timeline" icon={"\u{1F4C5}"}>
        <div className="space-y-3">
          {report.healthPeriodTimeline.map((hp, i) => (
            <div
              key={i}
              className={`rounded-lg p-3 border ${
                hp.type === "favorable"
                  ? "bg-green-500/5 border-green-500/10"
                  : hp.type === "cautious"
                  ? "bg-amber-500/5 border-amber-500/10"
                  : "bg-red-500/5 border-red-500/10"
              }${hp.isCurrent ? " ring-1 ring-amber-500/40" : ""}`}
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-sm font-semibold text-slate-200">
                  {hp.dashaLord}{hp.isCurrent ? " (Current)" : ""}
                </span>
                <span
                  className={`text-xs font-semibold ${
                    hp.type === "favorable"
                      ? "text-green-400"
                      : hp.type === "cautious"
                      ? "text-amber-400"
                      : "text-red-400"
                  }`}
                >
                  {hp.type === "favorable" ? "Favorable" : hp.type === "cautious" ? "Caution" : "Neutral"}
                </span>
              </div>
              <p className="text-xs text-slate-500">{hp.startDate} \u2013 {hp.endDate}</p>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">{hp.interpretation}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 10. Remedies */}
      <Section title="Remedies & Recommendations" icon={"\u{1F48E}"}>
        <div className="space-y-3">
          {report.remedies.map((r, i) => (
            <div key={i} className="bg-slate-800/30 rounded-lg p-3">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs bg-amber-500/10 text-amber-400 border border-amber-500/20 rounded-full px-2 py-0.5">
                  {r.category}
                </span>
                <span className="text-sm font-semibold text-slate-200">{r.title}</span>
              </div>
              <p className="text-xs text-slate-400 leading-relaxed">{r.description}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* Disclaimer */}
      <div className="bg-slate-800/30 border border-slate-700/50 rounded-xl p-4 text-center">
        <p className="text-xs text-slate-500 leading-relaxed">
          <strong className="text-slate-400">Disclaimer:</strong> This report is based on traditional
          Vedic astrology and Ayurvedic principles. It is for informational and wellness purposes only
          and does not constitute medical advice. Always consult qualified healthcare professionals
          for medical decisions.
        </p>
      </div>

      {/* Download PDF */}
      <div className="text-center space-x-3">
        <button
          onClick={() => downloadReportPdf(report, chart, name)}
          className="bg-amber-500 hover:bg-amber-400 text-black font-semibold px-6 py-2.5 rounded-lg transition-colors text-sm"
        >
          {"\u{1F4E5}"} Save as PDF
        </button>
        <button
          onClick={() => window.print()}
          className="text-sm text-slate-400 hover:text-slate-200 border border-slate-700 px-5 py-2.5 rounded-lg transition-colors"
        >
          {"\u{1F5A8}\uFE0F"} Print
        </button>
      </div>
    </div>
  );
}
